-- AlterTable
ALTER TABLE "StudentTotalFees" ADD COLUMN     "dueAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "status" TEXT NOT NULL DEFAULT 'Not Paid',
ADD COLUMN     "totalFeeAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
